// <auto-generated />
using System;
using CacheRedis.Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CacheRedis.Api.Migrations
{
    [DbContext(typeof(CotacaoContext))]
    partial class CotacaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CacheRedis.Api.Entities.Cotacao", b =>
                {
                    b.Property<int>("CotacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CotacaoId"));

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeMoeda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("CotacaoId");

                    b.ToTable("CotacoesAtual");
                });
#pragma warning restore 612, 618
        }
    }
}
